spring.application.name=accounts
spring.datasource.url=jdbc:h2:mem:accountsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=${JWT_SECRET:d2VsbGRlZmluaXRpb25taWdodHljdXJyZW50c2hvcnRlcnRoaW5rYWlkd2hvbGViaWw=}
jwt.expiration=${JWT_EXPIRATION:3600000}

admin.email=${ADMIN_EMAIL:admin@uowmail.edu.au}
admin.password=${ADMIN_PASSWORD:test123}
admin.username=${ADMIN_USERNAME:uow_admin}
server.port=8081

spring.kafka.bootstrap-servers=${KAFKA_SERVER_ACCOUNTS:localhost:9092}

spring.kafka.consumer.group-id=account-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.properties.spring.json.add.type.headers=true
spring.kafka.consumer.properties.spring.json.use.type.headers=true

spring.kafka.admin.auto-create=true
